repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
    - id: helmlint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
#      - id: go-unit-tests # doesn't work properly
      - id: go-build
      - id: go-mod-tidy
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
      - id: go-vet
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - name: govulncheck
        id: my-cmd-repo-mod
        args:
          - govulncheck
          - ./...
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.43.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
