apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-lease-reporter
  namespace: node-undertaker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-lease-reporter-node-reader
subjects:
  - kind: ServiceAccount
    name: node-lease-reporter
    namespace: node-undertaker
roleRef:
  kind: ClusterRole
  name: node-lease-reporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-lease-reporter
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-lease-reporter-lease-creator
  namespace: node-undertaker
subjects:

  - kind: ServiceAccount
    name: node-lease-reporter
    namespace: node-undertaker
roleRef:
  kind: Role
  name: node-lease-reporter
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-lease-reporter
  namespace: node-undertaker
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - create
      - patch

