apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-undertaker.fullname" . }}-controller
  labels:
    {{- include "node-undertaker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-undertaker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "node-undertaker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-undertaker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: CLOUD_PROVIDER
              value: {{ .Values.controller.settings.cloudProvider }}
            - name: NODE_INITIAL_THRESHOLD
              value: {{ .Values.controller.settings.nodeInitialThreshold | quote }}
            - name: CLOUD_TERMINATION_DELAY
              value: {{ .Values.controller.settings.cloudTerminationDelay | quote }}
            - name: DRAIN_DELAY
              value: {{ .Values.controller.settings.drainDelay | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.controller.settings.logLevel }}
            - name: LOG_FORMAT
              value: {{ .Values.controller.settings.logFormat }}
            - name: NODE_SELECTOR
              value: {{ .Values.controller.settings.nodeSelector | quote }}
            - name: PORT
              value: {{ .Values.controller.settings.port | quote }}
            {{- if .Values.controller.settings.leaseLockName }}
            - name: LEASE_LOCK_NAME
              value: {{ .Values.controller.settings.leaseLockName | quote }}
            {{- end }}
            {{- if .Values.controller.settings.leaseLockNamespace }}
            - name: LEASE_LOCK_NAMESPACE
              value: {{ .Values.controller.settings.leaseLockNamespace | quote }}
            {{- end }}
            {{- if .Values.controller.settings.namespace }}
            - name: NAMESPACE
              value: {{ .Values.controller.settings.namespace | quote }}
            {{- end }}
            {{- if .Values.controller.env }}
            {{- toYaml .Values.controller.env | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.controller.settings.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
