{{- if .Values.reporter.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-undertaker.fullname" . }}-reporter
subjects:
  - kind: ServiceAccount
    name: {{ include "node-undertaker-reporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "node-undertaker.fullname" . }}-reporter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-undertaker.fullname" . }}-reporter
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "node-undertaker.fullname" . }}-reporter-lease-creator
subjects:
  - kind: ServiceAccount
    name: {{ include "node-undertaker-reporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "node-undertaker.fullname" . }}-reporter
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "node-undertaker.fullname" . }}-reporter
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - create
      - patch
{{- end }}
