{{- if .Values.deployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-undertaker.serviceAccountName" . }}
  labels:
    {{- include "node-undertaker.labels" . | nindent 4 }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.reporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-undertaker-reporter.serviceAccountName" . }}
  labels:
    {{- include "node-undertaker-reporter.labels" . | nindent 4 }}
  {{- with .Values.reporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
