# Default values for node-undertaker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

controller:
  settings:
    cloudProvider: aws
    logLevel: info
    logFormat: json
#    leaseLockName: null
#    leaseLockNamespace: null
#    namespace: null
    nodeInitialThreshold: 120
    drainDelay: 300
    cloudTerminationDelay: 120
    cloudPrepareTerminationDelay: 300
    port: 8080
#    nodeLeaseNamespace: "kube-node-lease"
    nodeSelector: ""
    aws:
      region: ""
  replicaCount: 2

  pdb:
    enabled: true
    maxUnavailable: 1

  image:
    repository: node-undertaker #TODO set final value
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []

  rbac:
    # Specified if the roles and their bindings should be created
    create: true

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}
# to enable scraping metrics please uncomment those lines
#    prometheus.io/scrape: 'true'
#    prometheus.io/path: '/metrics'
#    prometheus.io/port: '8080'

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  env: []
