@startuml
hide empty description

state "Healthy" as healthy  #green;text:white
state "Label node" as label_node
label_node : label node with:\ndbschenker.com/node-undertaker=unhealthy
state "Taint node" as taint_node #yellow
taint_node : taint node with:\ndbschenker.com/node-undertaker:NoExecute
taint_node : label node with:\ndbschenker.com/node-undertaker=tainted
state "Drain node" as drain_node #orange
drain_node : label node with:\ndbschenker.com/node-undertaker=draining
drain_node : drain node
state "Terminating node" as terminating_node #red
terminating_node : label node with:\ndbschenker.com/node-undertaker=terminating
state "Terminating in the cloud" as terminate_in_the_cloud #brown;text:white
terminate_in_the_cloud : <color:white>remove resources from cloud provider

[*] --> healthy
healthy --> label_node : lease not refreshed
label_node --> taint_node : on update
taint_node --> drain_node : after "drain-delay" seconds
drain_node --> terminating_node : after "cloud-termination-delay" seconds
terminating_node -> terminate_in_the_cloud : on update
terminate_in_the_cloud --> [*]

label_node -[#green]-> healthy : <color:green>lease refreshed
taint_node -[#green]-> healthy : <color:green>lease refreshed
drain_node -[#green]-> healthy : <color:green>lease refreshed
@enduml
