@startuml
hide empty description

state "Healthy" as healthy  #green;text:white
state "Label node" as label_node
label_node : label node with:\ndbschenker.com/node-undertaker=unhealthy
state "Taint node" as taint_node #yellow
taint_node : taint node with:\ndbschenker.com/node-undertaker:NoExecute
taint_node : label node with:\ndbschenker.com/node-undertaker=tainted
state "Drain node" as drain_node #orange
drain_node : label node with:\ndbschenker.com/node-undertaker=draining
drain_node : drain node
state "Prepare node termination" as prepare_termination #red
prepare_termination : label node with:\ndbschenker.com/node-undertaker=prepare_termination
state "<color:white>Terminating node" as terminating_node #darkred;text:white
terminating_node : <color:white>label node with:\n<color:white>dbschenker.com/node-undertaker=terminating

[*] --> healthy
healthy --> label_node : lease not refreshed
label_node --> taint_node : on update
taint_node --> drain_node : after "drain-delay" seconds
drain_node --> prepare_termination : after "cloud-prepare-termination-delay" seconds
prepare_termination --> terminating_node : after "cloud-termination-delay"
terminating_node -->  [*]

label_node -[#green]-> healthy : <color:green>lease refreshed
taint_node -[#green]-> healthy : <color:green>lease refreshed
drain_node -[#green]-> healthy : <color:green>lease refreshed
@enduml