on:
  push:
    paths-ignore:
      - 'charts/**'
      - 'example/**'
      - 'docs/**'
      - '/*.md'
    branches:
      - '*'
  pull_request:
    paths-ignore:
      - 'example/**'
      - 'charts/**'
      - 'docs/**'
      - '/*.md'
  workflow_call:

name: Build and test
jobs:
  build:
    strategy:
      matrix:
        architecture: [amd64, arm64]
        os: [linux, darwin]

    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false # we use caching with actions/cache
        id: go

      - name: Cache Go modules packages
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download
        env:
          GOPROXY: https://proxy.golang.org

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{matrix.architecture}} go build ${{ env.LDFLAGS }} -o bin/node-undertaker-${{ matrix.os }}-${{ matrix.architecture }} ./cmd/node-undertaker

      - name: Test
        run: |
          go get github.com/golang/mock/mockgen
          go install github.com/golang/mock/mockgen
          go generate ./...
          go test ./...

      - uses: actions/upload-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          name: node-undertaker
          path: bin/node-undertaker-*
          if-no-files-found: error
