on:
  push:
    tags:
      - "v*.*.*"

name: Release
jobs:
  docker-build:
    uses: ./.github/workflows/docker.yml
  build-and-test:
    uses: ./.github/workflows/build.yml
  create-release:
    needs:
      - docker-build
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: node-undertaker-*
          path: bin
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          prerelease: ${{ contains(github.ref, 'rc') }}
          files: bin/node-undertaker*
          append_body: true
          body: |
            Build also available as docker image:
            `ghcr.io/${{ github.repository }}:${{ github.ref_name }}`
